INSERT INTO DEMOS(ID_DEMO, DS_DEMO) VALUES(1, 'DEMO #1');
INSERT INTO DEMOS(ID_DEMO, DS_DEMO) VALUES(2, 'DEMO #2');
INSERT INTO DEMOS(ID_DEMO, DS_DEMO) VALUES(3, 'DEMO #3');
INSERT INTO DEMOS(ID_DEMO, DS_DEMO) VALUES(4, 'DEMO #4');
INSERT INTO DEMOS(ID_DEMO, DS_DEMO) VALUES(5, 'DEMO #5');